### ISSUE TITLE
Security Vulnerability - Exposed API Token in Code

### ISSUE THREAD

**Issue by ludndev** [lasroun/Fetch2Excel#1]
Hey @lasroun  ! 👋

Hope you're all doing well! I've spotted something in our code that needs immediate attention - your API tokens are waving hello to the world from within the source code! It's here :

https://github.com/lasroun/Fetch2Excel/blob/ec01d1002586a4f9066477c1797b8346212c7a8a/export_crypto.py#L15

**Comment by lasroun** [comment]
Oh thank you very much  🙏🙏🙏🙏

Le mar. 12 déc. 2023 à 09:31, Judicaël AHYI ***@***.***> a
écrit :

**Comment by lasroun** [comment]
The correction has been made. The key was also changed on my side.
